version: '3.8'
services:
  quizzes_game_io_backend_postgres:
    container_name: quizzes_game_io_backend_postgres
    image: postgres:16.1
    user: root
    volumes:
      - quizzes_game_io_backend_data:/data/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: local
      POSTGRES_DB: quizzes_game_io_backend
      PGDATA: /data/postgres
      PGPORT: 5432
    ports:
      - 5432:5432

  quizzes_game_io_backend_redis:
    container_name: quizzes_game_io_backend_redis
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - quizzes_game_io_backend_redis_data:/data

volumes:
  quizzes_game_io_backend_data:
    driver: local
  quizzes_game_io_backend_redis_data:
    driver: local
