const APP = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  APP_STAGE: 'APP_STAGE',
} as const;

const DATABASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

const REDIS = {
  REDIS_URL: 'REDIS_URL',
};

const JWT = {
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_ISSUER: 'JWT_ISSUER',
  JWT_ACCESS_TOKEN_EXPIRES_IN: 'JWT_ACCESS_TOKEN_EXPIRES_IN',
} as const;

const LOGGER = {
  LOGGER_LEVEL: 'LOGGER_LEVEL',
} as const;

const AWS_S3 = {
  AWS_S3_REGION: 'AWS_S3_REGION',
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
  AWS_S3_URL: 'AWS_S3_URL',
  AWS_S3_ACCESS_KEY: 'AWS_S3_ACCESS_KEY',
  AWS_S3_SECRET_KEY: 'AWS_S3_SECRET_KEY',
  AWS_S3_IMAGE_FILE_PATH: 'AWS_S3_IMAGE_FILE_PATH',
} as const;

export const ENV_KEY = {
  ...APP,
  ...DATABASE,
  ...REDIS,
  ...JWT,
  ...LOGGER,
  ...AWS_S3,
} as const;
